### ISSUE TITLE
AppActivity example

### ISSUE THREAD

**Issue by jianingliu** [vertigis/vertigis-workflow-sdk#24]
Hi, 

I've been trying to follow [this tutorial](https://developers.vertigisstudio.com/docs/workflow/tutorial-web-add-layer-to-map) to develop an app activity for different layer types of Esri, but I think the tutorial might be outdated.

First, the AppActivity becomes a function in the new version (3.1), and I can't do this:
`class MyActivity extends AppActivity`

Even if I force that to happen by using @ts-ignore, it still does not work, because the this.map is undefined. 

So I just want to check if there's a new way in version 3 to do this, or did we just deprecated this feature?

Thanks,
Johnny

**Comment by kenlyon** [comment]
@jianingliu The `AppActivity` class was intentionally re-written as a function to solve a different problem. It fixed a problem with older activity packs that weren't working in VertiGIS Studio Web. However, it sounds like we need to adapt it further to work in both cases. I will look into this.

**Comment by kenlyon** [comment]
@jianingliu I can confirm there is a problem here that we need to fix. We need to include additional type information to satisfy TypeScript that you can extend this class.

In the meantime, there might be another solution to your problem. Are you aware of our [@vertigis/workflow-activities-arcgis-core](https://github.com/vertigis/workflow-activities-arcgis-core#readme) activity pack? It contains some activities that might help with what you're trying to achieve:

* [AddLayerToMap](https://github.com/vertigis/workflow-activities-arcgis-core/blob/main/src/activities/AddLayerToMap.ts)
* [CreateLayerFromArcGisServerUrl](https://github.com/vertigis/workflow-activities-arcgis-core/blob/main/src/activities/CreateLayerFromArcGisServerUrl.ts)

If not, you can still write your own. Take a look at how AddLayerToMap uses `@activate(MapProvider)` to interact with the map.

**Comment by kenlyon** [comment]
@jianingliu That should be it sorted for you now. Just make sure when you run the `npx` command to create an activity pack that you have `@latest` to make sure you don't get a cached version of the SDK:
```
npx @vertigis/workflow-sdk@latest create my-activity-pack
```
If you have an existing activity pack that you want to upgrade, you can manually change the version of `@vertigis/workflow` in the `package.json` file to `"5.32.1"`.
